#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

ERROR_FILES=''

which eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m"
  exit 1
fi

for FILE in $STAGED_FILES
do
  eslint "$FILE"
  if [[ "$?" != 0 ]]; then
      ERROR_FILES="${ERROR_FILES} \t ${FILE}"
  fi
done
if [[ $ERROR_FILES != '' ]];  then
  echo "\033[41mCOMMIT FAILED:\033[0m Please fix the lint issues in these files.\n $ERROR_FILES"
  exit 1
fi

echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
exit $?